import Providers from '@/app/utils/Providers';
import Layout from '@/layouts/layout/Layout';
import { pretendard } from '@/utils/fonts';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '월드코리아',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} ${pretendard.className}`}>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
