import ReactQueryProviders from '@/app/utils/ReactQueryProvider';
import Layout from '@/layouts/layout/Layout';
import { pretendard } from '@/utils/fonts';
import type { Metadata } from 'next';
import './globals.css';
import SessionProvider from './utils/SessionProvider';

export const metadata: Metadata = {
  title: '월드코리아',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="ko">
        <body className={`${pretendard.variable} ${pretendard.className}`}>
          <ReactQueryProviders>
            <Layout>{children}</Layout>
          </ReactQueryProviders>
        </body>
      </html>
    </SessionProvider>
  );
}
